 Can not obtain ownership information
  TCP    192.168.249.49:59658   192.168.199.186:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59659   192.168.199.187:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59660   192.168.199.188:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59661   192.168.199.189:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59662   192.168.199.190:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59663   192.168.199.191:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59664   192.168.199.192:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59665   192.168.199.193:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59666   192.168.199.194:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59667   192.168.199.195:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59668   192.168.199.196:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59669   192.168.199.197:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59670   192.168.199.198:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59671   192.168.199.199:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59672   192.168.199.200:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59673   192.168.199.201:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59674   192.168.199.202:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59675   192.168.199.203:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59676   192.168.199.204:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59677   192.168.199.205:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59678   192.168.199.206:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59679   192.168.199.207:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59680   192.168.199.208:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59681   192.168.199.209:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59682   192.168.199.210:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59683   192.168.199.211:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59684   192.168.199.212:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59685   192.168.199.213:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59686   192.168.199.214:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59687   192.168.199.215:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59688   192.168.199.216:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59689   192.168.199.217:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59690   192.168.199.218:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59691   192.168.199.219:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59692   192.168.199.220:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59693   192.168.199.221:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59694   192.168.199.222:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59695   192.168.199.223:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59696   192.168.199.224:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59697   192.168.199.225:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59698   192.168.199.226:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59699   192.168.199.227:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59700   192.168.199.228:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59701   192.168.199.229:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59702   192.168.199.230:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59703   192.168.199.231:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59704   192.168.199.232:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59705   192.168.199.233:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59706   192.168.199.234:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59707   192.168.199.235:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59708   192.168.199.236:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59709   192.168.199.237:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59710   192.168.199.238:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59711   192.168.199.239:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59712   192.168.199.240:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59713   192.168.199.241:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59714   192.168.199.242:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59715   192.168.199.243:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59716   192.168.199.244:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:59717   192.168.199.245:microsoft-ds  SYN_SENT
 Can not obtain ownership information
  TCP    192.168.249.49:65424   dd-in-f188.1e100.net:5228  ESTABLISHED
 [chrome.exe]
  TCP    [::]:7                 mylocyrus:0            LISTENING
 [tcpsvcs.exe]
  TCP    [::]:9                 mylocyrus:0            LISTENING
 [tcpsvcs.exe]
  TCP    [::]:13                mylocyrus:0            LISTENING
 [tcpsvcs.exe]
  TCP    [::]:17                mylocyrus:0            LISTENING
 [tcpsvcs.exe]
  TCP    [::]:19                mylocyrus:0            LISTENING
 [tcpsvcs.exe]
  TCP    [::]:80                mylocyrus:0            LISTENING
 Can not obtain ownership information
  TCP    [::]:135               mylocyrus:0            LISTENING
  RpcSs
 [svchost.exe]
  TCP    [::]:445               mylocyrus:0            LISTENING
 Can not obtain ownership information
  TCP    [::]:3587              mylocyrus:0            LISTENING
  p2pimsvc
 [svchost.exe]
  TCP    [::]:5357              mylocyrus:0            LISTENING
 Can not obtain ownership information
  TCP    [::]:49152             mylocyrus:0            LISTENING
 [wininit.exe]
  TCP    [::]:49153             mylocyrus:0            LISTENING
  eventlog
 [svchost.exe]
  TCP    [::]:49154             mylocyrus:0            LISTENING
  Schedule
 [svchost.exe]
  TCP    [::]:49158             mylocyrus:0            LISTENING
 [services.exe]
  TCP    [::]:49159             mylocyrus:0            LISTENING
 [lsass.exe]
  TCP    [2607:fb91:68c:515d:e1ba:d3b4:6f95:ac5c]:49504  [64:ff9b::2d5a:d862]:ht
tp  CLOSE_WAIT
 [audiodg.exe]
  TCP    [2607:fb91:68c:515d:e1ba:d3b4:6f95:ac5c]:49649  [64:ff9b::2d5a:d862]:ht
tp  CLOSE_WAIT
 [audiodg.exe]
  TCP    [2607:fb91:68c:515d:e1ba:d3b4:6f95:ac5c]:61230  [64:ff9b::2d5a:d862]:ht
tp  CLOSE_WAIT
 [taskhost.exe]
  TCP    [2607:fb91:68c:515d:e1ba:d3b4:6f95:ac5c]:62139  [2607:7700:0:35:0:1:a2f
f:7755]:http  CLOSE_WAIT
 [taskhost.exe]
  TCP    [2607:fb91:68c:515d:e1ba:d3b4:6f95:ac5c]:62387  dl-in-f188.1e100.net:52
28  ESTABLISHED
 [chrome.exe]
  TCP    [2607:fb91:68c:515d:e1ba:d3b4:6f95:ac5c]:62557  g2600-1409-5000-049a-00
00-0000-0000-3433.deploy.static.akamaitechnologies.com:https  CLOSE_WAIT
 [CCleaner64.exe]
  UDP    0.0.0.0:7              *:*
 [tcpsvcs.exe]
  UDP    0.0.0.0:9              *:*
 [tcpsvcs.exe]
  UDP    0.0.0.0:13             *:*
 [tcpsvcs.exe]
  UDP    0.0.0.0:17             *:*
 [tcpsvcs.exe]
  UDP    0.0.0.0:19             *:*
 [tcpsvcs.exe]
  UDP    0.0.0.0:161            *:*
 [snmp.exe]
  UDP    0.0.0.0:500            *:*
  IKEEXT
 [svchost.exe]
  UDP    0.0.0.0:3702           *:*
  EventSystem
 [svchost.exe]
  UDP    0.0.0.0:3702           *:*
  FDResPub
 [svchost.exe]
  UDP    0.0.0.0:3702           *:*
  FDResPub
 [svchost.exe]
  UDP    0.0.0.0:3702           *:*
  EventSystem
 [svchost.exe]
  UDP    0.0.0.0:4500           *:*
  IKEEXT
 [svchost.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5355           *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:52378          *:*
  EventSystem
 [svchost.exe]
  UDP    0.0.0.0:61717          *:*
  FDResPub
 [svchost.exe]
  UDP    0.0.0.0:61719          *:*
  EventSystem
 [svchost.exe]
  UDP    127.0.0.1:1900         *:*
  SSDPSRV
 [svchost.exe]
  UDP    127.0.0.1:54333        *:*
  SSDPSRV
 [svchost.exe]
  UDP    192.168.249.49:137     *:*
 Can not obtain ownership information
  UDP    192.168.249.49:138     *:*
 Can not obtain ownership information
  UDP    192.168.249.49:1900    *:*
  SSDPSRV
 [svchost.exe]
  UDP    192.168.249.49:49290   *:*
 [chrome.exe]
  UDP    192.168.249.49:54332   *:*
  SSDPSRV
 [svchost.exe]
  UDP    [::]:7                 *:*
 [tcpsvcs.exe]
  UDP    [::]:9                 *:*
 [tcpsvcs.exe]
  UDP    [::]:13                *:*
 [tcpsvcs.exe]
  UDP    [::]:17                *:*
 [tcpsvcs.exe]
  UDP    [::]:19                *:*
 [tcpsvcs.exe]
  UDP    [::]:161               *:*
 [snmp.exe]
  UDP    [::]:500               *:*
  IKEEXT
 [svchost.exe]
  UDP    [::]:3540              *:*
  p2pimsvc
 [svchost.exe]
  UDP    [::]:3702              *:*
  FDResPub
 [svchost.exe]
  UDP    [::]:3702              *:*
  FDResPub
 [svchost.exe]
  UDP    [::]:3702              *:*
  EventSystem
 [svchost.exe]
  UDP    [::]:3702              *:*
  EventSystem
 [svchost.exe]
  UDP    [::]:4500              *:*
  IKEEXT
 [svchost.exe]
  UDP    [::]:5353              *:*
 [chrome.exe]
  UDP    [::]:5355              *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:52379             *:*
  EventSystem
 [svchost.exe]
  UDP    [::]:61718             *:*
  FDResPub
 [svchost.exe]
  UDP    [::]:61720             *:*
  EventSystem
 [svchost.exe]
  UDP    [::1]:1900             *:*
  SSDPSRV
 [svchost.exe]
  UDP    [::1]:54331            *:*
  SSDPSRV
 [svchost.exe]
  UDP    [fe80::31cc:fd88:28fd:aa5e%15]:1900  *:*
  SSDPSRV
 [svchost.exe]
  UDP    [fe80::31cc:fd88:28fd:aa5e%15]:54330  *:*
  SSDPSRV
 [svchost.exe]

C:\Users\mylo>
